language: python
python:
 - "2.6"
 - "2.7"
install: pip install -r requirements.txt -r optional.txt --use-mirrors
script: DJANGO_SETTINGS_MODULE='django_statsd.test_settings' nosetests
notifications:
  irc: "irc.mozilla.org#amo-bots"
