language: python
env:
 - DJANGO=1.6
 - DJANGO=1.7
python:
 - "2.6"
 - "2.7"
 - "pypy"
install:
 - pip install -r requirements.txt -r optional.txt --use-mirrors
 - pip install "Django<${DJANGO}" --use-mirrors
script: DJANGO_SETTINGS_MODULE='django_statsd.test_settings' nosetests
notifications:
  irc: "irc.mozilla.org#amo-bots"
